In [68]:
import pandas as pd
import numpy as np

budgets = pd.read_excel("Budgets.xlsx")


# Rename the columns to date and budget
budgets.rename(columns = {
    "Date": "date",
    "Budget": "budget"
},inplace=True)

budgets.head()

        date   budget
0 2022-01-01   800000
1 2022-02-01   800000
2 2022-03-01  1000000
3 2022-04-01  1000000
4 2022-05-01  1100000

In [69]:
calendars = pd.read_csv("calendar.csv")
calendars.head()


# Rename the columns 
calendars.rename(columns = {
    "DateKey": "datekey",
    "Date": "date",
    "Day": "day",
    "Month": "month",
    "Year": "year",
    "MonthShort": "monthshort",
    "MonthNo": "monthno",
    "Quarter": "quarter",
    "WeekNr": "weeknr"
},inplace=True)


# Removing the columns that are not needed
calendars = calendars.drop(columns = ["datekey", "month"])

calendars["date"] = pd.to_datetime(calendars["date"], dayfirst=True, errors="coerce")
# print(calendars.dtypes)
print(calendars.head())

        date        day  weeknr monthshort  monthno  quarter  year
0 2019-01-01    Tuesday       1        Jan        1        1  2019
1 2019-01-02  Wednesday       1        Jan        1        1  2019
2 2019-01-03   Thursday       1        Jan        1        1  2019
3 2019-01-04     Friday       1        Jan        1        1  2019
4 2019-01-05   Saturday       1        Jan        1        1  2019

In [70]:
customers = pd.read_csv("customers.csv")
customers.head()

,CustomerKey,First_Name,Last_Name,Full_Name,Gender,DateFirstPurchase,Customer_City
0,11000,Jon,Yang,Jon Yang,Male,19/1/2021,Rockhampton
1,11001,Eugene,Huang,Eugene Huang,Male,15/1/2021,Seaford
2,11002,Ruben,Torres,Ruben Torres,Male,7/1/2021,Hobart
3,11003,Christy,Zhu,Christy Zhu,Female,29/12/2020,North Ryde
4,11004,Elizabeth,Johnson,Elizabeth Johnson,Female,23/1/2021,Wollongong

In [71]:
customers = pd.read_csv("customers.csv")
print(customers.head())

# Rename the columns 

#customers.columns = customers.columns.str.strip()
customers.rename(columns = {
    "CustomerKey": "customer_key",
    "First_Name": "first_name",
    "Last_Name": "last_name",
    "Full_Name": "full_name",
    "Gender": "gender",
    "DateFirstPurchase": "date_first_purchase",
    "Customer_City": "customer_city"
},inplace=True)

customers["date_first_purchase"] = pd.to_datetime(customers["date_first_purchase"], dayfirst=True, errors="coerce")
print(customers.dtypes)

   CustomerKey First_Name Last_Name          Full_Name  Gender  \
0        11000        Jon      Yang           Jon Yang    Male
1        11001     Eugene     Huang       Eugene Huang    Male
2        11002      Ruben    Torres       Ruben Torres    Male
3        11003    Christy       Zhu        Christy Zhu  Female
4        11004  Elizabeth   Johnson  Elizabeth Johnson  Female

  DateFirstPurchase Customer_City
0         19/1/2021   Rockhampton
1         15/1/2021       Seaford
2          7/1/2021        Hobart
3        29/12/2020    North Ryde
4         23/1/2021    Wollongong
customer_key                    int64
first_name                     object
last_name                      object
full_name                      object
gender                         object
date_first_purchase    datetime64[ns]
customer_city                  object
dtype: object

In [76]:
internet_sales = pd.read_csv("internet_sales.csv")
internet_sales.head()

internet_sales.rename(columns = {
    "ProductKey": "product_key",
    "OrderDateKey": "order_date_key",
    "DueDateKey": "due_date_key",
    "ShipDateKey": "ship_date_key",
    "CustomerKey": "customer_key",
    "SalesOrderNumber": "sales_order_number",
    "SalesAmount": "sales_amount"
},inplace=True)

date_col = ["order_date_key", "due_date_key", "ship_date_key"]
for col in date_col:
    internet_sales[col] = pd.to_datetime(internet_sales[col], dayfirst=True, errors="coerce")
    
print(internet_sales.dtypes)

product_key                    int64
order_date_key        datetime64[ns]
due_date_key          datetime64[ns]
ship_date_key         datetime64[ns]
customer_key                   int64
sales_order_number            object
sales_amount                 float64
dtype: object