In [ ]:
import pandas as pd

travel_package = pd.read_csv("gs://ppnj_data/files/dim_travel_package.csv")
travel_package.head()

,package_id,package_name,package_type,duration_days,price_per_pax,category,destination
0,PC10,Manila,solo,6,2387,adventure,Manila
1,PC11,Krabi,group,4,2256,eco,Krabi
2,PC12,Taman Negara,solo,2,1018,adventure,Taman Negara
3,PC13,Putrajaya,family,3,763,adventure,Putrajaya
4,PC14,Cebu,family,5,1784,cultural,Cebu

In [ ]:
travel_package.shape

(39, 7)

In [ ]:
destination = travel_package['destination'].to_list()
print(destination)

destination_url = ['https://images.unsplash.com/photo-1555557356-51c5d7a8f4c2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bWFuaWxhfGVufDB8fDB8fHww',
                   'https://images.unsplash.com/photo-1710005631041-a0efc9795e8f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8a3JhYml8ZW58MHx8MHx8fDA%3D',
                   'https://media.istockphoto.com/id/1132151513/photo/berkoh-years.webp?a=1&b=1&s=612x612&w=0&k=20&c=9Wy9OpGeArq-kBMrhkgbK7cBuIsoDznKU14XUJtyVaA=',
                   'https://images.unsplash.com/photo-1491120644131-be1e495526b9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cHV0cmFqYXlhfGVufDB8fDB8fHww',
                   'https://images.unsplash.com/photo-1495443942462-81f29560f7e0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2VidXxlbnwwfHwwfHx8MA%3D%3D',
                   'https://images.unsplash.com/photo-1617171985982-c8453a5ee5eb?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGJhZ2FufGVufDB8fDB8fHww',
                   'https://images.unsplash.com/photo-1654180674739-4151c5e7ee69?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHB1bGF1JTIwc2lwYWRhbnxlbnwwfHwwfHx8MA%3D%3D',
                   'https://images.unsplash.com/photo-1580229045710-e7054cb2ea5d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8amFrYXJ0YXxlbnwwfHwwfHx8MA%3D%3D',
                   'https://plus.unsplash.com/premium_photo-1700955004555-900a9733ee14?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8eW9neWFrYXJ0YXxlbnwwfHwwfHx8MA%3D%3D',
                   'https://images.unsplash.com/photo-1601225612316-b4733315a717?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cGh1a2V0fGVufDB8fDB8fHww',
                   'https://images.unsplash.com/photo-1555557356-51c5d7a8f4c2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bWFuaWxhfGVufDB8fDB8fHww',
                   'https://images.unsplash.com/photo-1710005631041-a0efc9795e8f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8a3JhYml8ZW58MHx8MHx8fDA%3D',
                   'https://media.istockphoto.com/id/1132151513/photo/berkoh-years.webp?a=1&b=1&s=612x612&w=0&k=20&c=9Wy9OpGeArq-kBMrhkgbK7cBuIsoDznKU14XUJtyVaA=',
                   'https://images.unsplash.com/photo-1491120644131-be1e495526b9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cHV0cmFqYXlhfGVufDB8fDB8fHww',
                   'https://images.unsplash.com/photo-1495443942462-81f29560f7e0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2VidXxlbnwwfHwwfHx8MA%3D%3D',
                   'https://images.unsplash.com/photo-1617171985982-c8453a5ee5eb?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGJhZ2FufGVufDB8fDB8fHww',
                   'https://images.unsplash.com/photo-1654180674739-4151c5e7ee69?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHB1bGF1JTIwc2lwYWRhbnxlbnwwfHwwfHx8MA%3D%3D',
                   'https://images.unsplash.com/photo-1580229045710-e7054cb2ea5d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8amFrYXJ0YXxlbnwwfHwwfHx8MA%3D%3D',
                   'https://plus.unsplash.com/premium_photo-1700955004555-900a9733ee14?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8eW9neWFrYXJ0YXxlbnwwfHwwfHx8MA%3D%3D',
                   'https://images.unsplash.com/photo-1601225612316-b4733315a717?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cGh1a2V0fGVufDB8fDB8fHww',
                   'https://images.unsplash.com/photo-1555557356-51c5d7a8f4c2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bWFuaWxhfGVufDB8fDB8fHww',
                   'https://images.unsplash.com/photo-1710005631041-a0efc9795e8f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8a3JhYml8ZW58MHx8MHx8fDA%3D',
                   'https://media.istockphoto.com/id/1132151513/photo/berkoh-years.webp?a=1&b=1&s=612x612&w=0&k=20&c=9Wy9OpGeArq-kBMrhkgbK7cBuIsoDznKU14XUJtyVaA=',
                   'https://images.unsplash.com/photo-1491120644131-be1e495526b9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cHV0cmFqYXlhfGVufDB8fDB8fHww',
                   'https://images.unsplash.com/photo-1495443942462-81f29560f7e0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2VidXxlbnwwfHwwfHx8MA%3D%3D',
                   'https://images.unsplash.com/photo-1617171985982-c8453a5ee5eb?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGJhZ2FufGVufDB8fDB8fHww',
                   'https://images.unsplash.com/photo-1654180674739-4151c5e7ee69?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHB1bGF1JTIwc2lwYWRhbnxlbnwwfHwwfHx8MA%3D%3D',
                   'https://images.unsplash.com/photo-1580229045710-e7054cb2ea5d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8amFrYXJ0YXxlbnwwfHwwfHx8MA%3D%3D',
                   'https://plus.unsplash.com/premium_photo-1700955004555-900a9733ee14?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8eW9neWFrYXJ0YXxlbnwwfHwwfHx8MA%3D%3D',
                   'https://images.unsplash.com/photo-1601225612316-b4733315a717?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cGh1a2V0fGVufDB8fDB8fHww',
                   'https://images.unsplash.com/photo-1555557356-51c5d7a8f4c2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bWFuaWxhfGVufDB8fDB8fHww',
                   'https://images.unsplash.com/photo-1710005631041-a0efc9795e8f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8a3JhYml8ZW58MHx8MHx8fDA%3D',
                   'https://media.istockphoto.com/id/1132151513/photo/berkoh-years.webp?a=1&b=1&s=612x612&w=0&k=20&c=9Wy9OpGeArq-kBMrhkgbK7cBuIsoDznKU14XUJtyVaA=',
                   'https://images.unsplash.com/photo-1491120644131-be1e495526b9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cHV0cmFqYXlhfGVufDB8fDB8fHww',
                   'https://images.unsplash.com/photo-1495443942462-81f29560f7e0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2VidXxlbnwwfHwwfHx8MA%3D%3D',
                   'https://images.unsplash.com/photo-1617171985982-c8453a5ee5eb?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGJhZ2FufGVufDB8fDB8fHww',
                   'https://images.unsplash.com/photo-1654180674739-4151c5e7ee69?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHB1bGF1JTIwc2lwYWRhbnxlbnwwfHwwfHx8MA%3D%3D',
                   'https://images.unsplash.com/photo-1580229045710-e7054cb2ea5d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8amFrYXJ0YXxlbnwwfHwwfHx8MA%3D%3D',
                   'https://plus.unsplash.com/premium_photo-1700955004555-900a9733ee14?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8eW9neWFrYXJ0YXxlbnwwfHwwfHx8MA%3D%3D']

print(len(destination_url))

['Manila', 'Krabi', 'Taman Negara', 'Putrajaya', 'Cebu', 'Bagan', 'Pulau Sipadan', 'Jakarta', 'Yogyakarta', 'Phuket', 'Nha Trang', 'Siem Reap', 'Melaka', 'Cameron Highlands', 'Kota Kinabalu', 'Ho Chi Minh City', 'Penang', 'Dili', 'Halong Bay', 'Pulau Redang', 'Vientiane', 'Yangon', 'Hanoi', 'Langkawi', 'Singapore', 'Brunei', 'Kuala Lumpur', 'Boracay', 'Lombok', 'Bali', 'Phnom Penh', 'Komodo Island', 'Pulau Perhentian', 'Sapa', 'Pulau Tioman', 'Borneo', 'Bangkok', 'Chiang Mai', 'Luang Prabang']
39

In [ ]:
# generate df

destination_images = pd.DataFrame({
    'destination': destination,
    'destination_url': destination_url

})

destination_images.head()

    destination                                    destination_url
0        Manila  https://images.unsplash.com/photo-1555557356-5...
1         Krabi  https://images.unsplash.com/photo-171000563104...
2  Taman Negara  https://media.istockphoto.com/id/1132151513/ph...
3     Putrajaya  https://images.unsplash.com/photo-149112064413...
4          Cebu  https://images.unsplash.com/photo-149544394246...

In [13]:
# Save as csv in gcs

destination_images.to_csv(
    'gs://ppnj_data/files/destination_images.csv',
    index=False,
    storage_options={"token": "cloud"}
)